
services:
  orchestrator-service:
    build: ./orchestrator-service
    container_name: orchestrator-service
    ports:
      - "8000:8000"
    depends_on:
      - stt-service
      - llm-service
      - tts-service
      - validation-service
      - validation-service
      - ui-service
      - ollama

  stt-service:
    build: ./stt-service
    container_name: stt-service
    ports:
      - "8001:8000"
    volumes:
      - ./stt_models:/root/.cache

  llm-service:
    build: ./llm-service
    container_name: llm-service
    ports:
      - "8003:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  tts-service:
    build: ./tts-service
    container_name: tts-service
    ports:
      - "8002:8000"
    volumes:
      - ./tts_models:/root/.cache

  validation-service:
    build: ./validation-service
    container_name: validation-service
    ports:
      - "8004:8000"

  ui-service:
    build: ./ui
    container_name: ui-service
    ports:
      - "7860:7860"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
      - ./ollama-entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
